navbar:
  enable: true
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: https://cdn.nxingcloud.co/images/logo/icon/logo-5-209a13.png # 导航栏首个图标
    icon:
    title:
  menu:
    - name: 首页
      icon: iconfont icon-shouye
      url: /
    - name: 分类
      icon: iconfont icon-fenlei-
      url: categories/
    - name: 归档
      icon: iconfont icon-guidang
      url: archives/
    - name: 友链
      icon: iconfont icon-lianjie
      url: friends/
    # - name: 关于
    #   icon: fa-solid fa-info-circle
    #   url: about/
    - name: 暗黑模式 # 可自定义
      icon: fa-solid fa-moon # 可自定义
      toggle: darkmode

nextNavbar:
  # subtitle: 繁星永存，记忆亘古不变。
  # menu:
  #   - name: '- 首页 °| Home'
  #     icon: 'iconfont icon-shouye'  # 'fa-light fa-home'
  #     url: /
  #   - name: '- 分类 °| Categories'
  #     icon: 'iconfont icon-fenlei-' # 'fa-light fa-th'
  #     url: /categories/
  #   - name: '- 归档 °| Archives'
  #     icon: 'iconfont icon-guidang' # 'fa-light fa-archive'
  #     url: /archives/
  #   # - name: '- 留言 °| Message'
  #   #   icon: 'iconfont icon-liuyan' # 'fa-light fa-object-group'
  #   #   url: /page/info/
  #   - name: '- 友链 °| Friends'
  #     icon: 'iconfont icon-lianjie' # 'fa-light fa-link'
  #     url: /friends/
  #   # - name: '- 生活 °| Blogger'
  #   #   icon: 'fa-light fa-ghost'
  #   #   url: https://szyink.com/
  #   # - name: '- 虫洞 °| Wormhole'
  #   #   icon: 'fa-light fa-bullseye-pointer'
  #   #   url: https://www.foreverblog.cn/go.html
  #   #   target: '_blank'  
  #   - name: '- 搜索 °| Search'
  #     icon: 'iconfont icon-sousuo' # 'fa-light fa-search'
  #     url: 'javascript:void(0)'
  #     click: 'OpenSearch()'

cover:
  height_scheme: full # full, half
  layout_scheme: dock # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display: # 封面展示
    home: true
    archive: false
    others: false # can be written in front-matter 'cover: true'
  background: https://api.nxingcloud.co/bing/?rand=true
  logo: https://cdn.nxingcloud.co/images/logo/gravatar/circleedgelogo-855aa71c.png?image
  title: 'Venil'
  subtitle: 'Code Creats Life.'
  search: The world is going to get better # search bar placeholder
  features:
    # - name: 主页
    #   icon: #
    #   img: http://rh651xal8.hd-bkt.clouddn.com/img/pagelogo2.svg?image # https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
    #   url: 
    - name: 博客
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: https://nxingcloud.co/
    - name: 文件
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://one.nxingcloud.co/
    - name: 壁纸
      icon: #
      img: https://cdn.nxingcloud.co/images/logo/icon/icons8-bing-32-e3c7cf370294576ae48fbb4625e8002c-76fa00.ico #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://bing.nxingcloud.co/
    - name: 云盘
      icon: #
      img: https://cdn.nxingcloud.co/images/logo/icon/Cloudlogo-f84213fc.ico?image # http://rh651xal8.hd-bkt.clouddn.com/img/Cloudlogo6.ico?image # 
      url: https://pan.nxingcloud.co/
############################### Cover ############################### > end

pages:
  # 友链页面配置
  friends:
    layout_scheme: simple # simple: 简单布局, traditional: 传统布局

# 文章布局
article:
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, category, date, artalkcount] #启用评论数量需在此添加
    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [updated, tags, counter, share]
    # 文章页脚组件
    footer_widget:
      # 版权声明组件 (for layout: post)
      copyright:
        enable: true

    meta_library:
      # 默认文章作者（可在 _data/author.yaml 中增加其他作者，并在 front-matter 中设置）
      # https://volantis.js.org/advanced-settings/#多人协同
      author:
        avatar: https://cdn.nxingcloud.co/images/logo/gravatar/circleedgelogo-855aa71c.png?image # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png
        name: 南星&NXing
        url: /

comments:
  title: <i class='fa-solid fa-comments'></i> 评论
  service: artalk
  # 可选评论系统 #
  artalk:
    js: https://cdn.nxingcloud.co/assets/style/artalk/Artalk-b5b3a442.js   # or https://unpkg.com/artalk@2.2.8/dist/Artalk.js
    css: https://cdn.nxingcloud.co/assets/style/artalk/Artalk-2a1f8b36.css # or https://unpkg.com/artalk@2.2.8/dist/Artalk.css
    server: https://artalk.nxingcloud.co # 修改为自建的后端服务地址
    path:  # 全局评论地址
    placeholder: # 评论占位
    emoticons: 
    - "https://cdn.nxingcloud.co/assets/emoji/bilibili2233/bilibili2233-695ddd75ffd2f17e401c4b1642c67492-71d0f6.json"
    - "https://cdn.nxingcloud.co/assets/emoji/Tieba/Tieba-a74dcc7cda7f5b2a876e01ceaa82af09-cc8d29.json"


sidebar:
  position: left # left right
  # 主页、分类、归档等独立页面
  for_page: [blogger, artalk, lastupdate]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger: 
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: https://cdn.nxingcloud.co/images/logo/gravatar/circleedgelogo-855aa71c.png?image
      shape: circle # circle, rectangle
      url: /about/
      title: 南星&NXing
      social:
        - icon: fa-solid fa-circle-user
          url: https://me.nxingcloud.co/
        - icon: fa-solid fa-envelope
          url: mailto:z1304242002@163.com
        - icon: fab fa-github
          url: https://github.com/ZhangXQA/
        - icon: fa-solid fa-headphones-alt
          url: https://music.163.com/#/playlist?id=647135926/
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      list_number: false
    # ---------------------------------------
     # music
    music:
      class: music
      pjaxReload: false # 切换页面时音乐不切换，继续播放
    # ---------------------------------------
    # category widget
    category:
      class: category
      header:
        title: 文章分类
        url: /categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      header:
        title: 热门标签
        url: /tags/
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2022/05/12'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          service: # leancloud # busuanzi, leancloud
    # Artalk widget
    artalk:
      class: artalk
      sticky: true
      display: [desktop]
    # ---------------------------------------
    # nextsite widget
    nextsite:
      class: nextsite
      display: [desktop, mobile]

############################### Site Footer ############################### > start
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [social, license, Upai, shilds, copyright, beian]
  social:
    - icon: fa fa-home
      url: https://me.nxingcloud.co/
    - icon: fas fa-envelope
      url: mailto:z1304242002@163.com
    - icon: fab fa-github
      url: https://github.com/ZhangXQA/
  beian: <a href="https://beian.miit.gov.cn/" target="_blank">冀ICP备2022019815号-1</a>
  Upai: <a href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral/">本站由 <img src="https://cdn.nxingcloud.co/images/logo/icon/upai-bf0d7cd0.png?image" alt="又拍云" width="59" height="30" style="vertical-align:middle"> 提供CDN加速/云存储服务</a>
  shilds: '[![](https://img.shields.io/badge/Powered-Hexo-blue.svg)](https://hexo.io/zh-cn/)        [![](https://img.shields.io/badge/Theme-Volantis-success.svg)](https://volantis.js.org/)'
  # site copyright
  copyright: '[政策](https://nxingcloud.co/pages/policy/) | Copyright © 2022 <i class="fa fa-heartbeat" aria-hidden="true" style="color:red"></i> [南星&NXing](/)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '[Powered by Hexo and Volantis](/)'

############################### Plugins ############################### > start
plugins:
  # npm i hexo-wordcount
  wordcount:
    enable: false
  # Button Ripple Effect
  nodewaves:
    enable: true
  # fontawesome animation for fontawesome V5
  fontawesome_animation:
    enable: true
  # Typing Effects
  comment_typing:
    enable: false
  # 视差滚动效果 Slide Background
  parallax:
    enable: false

  code_highlight: highlightjs # highlightjs or prismjs
  # highlight.js
  highlightjs:
    copy_code: true
    js: https://unpkg.com/@highlightjs/cdn-assets@11.5.1/highlight.min.js # Please set hexo.config.highlight.enable = false !!!
    css: https://cdn.jsdelivr.net/npm/highlight.js@11.6.0/styles/atom-one-dark.css # https://unpkg.com/@highlightjs/cdn-assets@11.5.1/styles/default.min.css

  aplayer:
    enable: false
    
  darkmode:
    enable: true

# 消息提示 
  # izitoast@1.4.0
  message:
    copyright:                           # 是否在复制时弹出版权提示，影响范围：ctrl+c、代码块复制按钮、右键复制选项
      enable: true
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'far fa-copyright light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red

### 自定义右键 新
rightmenus:
  enable: true
  # 右键自定义菜单区域
  menus:
    link:
      - {id: 'contact_the_author', name: '联系作者', icon: 'fa-solid fa-envelope', link: '/about', group: 'link'}
    #  - {id: 'help', name: '常见问题', icon: 'fa-solid fa-question', link: 'https://volantis.js.org/faqs/', group: 'link'}
    #  - {id: 'examples', name: '示例博客', icon: 'fa-solid fa-rss', link: 'https://volantis.js.org/examples/', group: 'link'}
    #  - {id: 'contributors', name: '加入社区', icon: 'fa-solid fa-fan', link: 'https://volantis.js.org/contributors/', group: 'link'}
      - hr
    #  - {id: 'source_docs', name: '本站源码', icon: 'fa-solid fa-code-branch', link: 'https://github.com/volantis-x/volantis-docs/', group: 'link'}
    #  - {id: 'source_theme', name: '主题源码', icon: 'fa-solid fa-code-branch', link: 'https://github.com/volantis-x/hexo-theme-volantis/', group: 'link'}
    darkMode:
      - {id: 'darkMode', name: '暗黑模式', icon: 'fa-solid fa-moon', event: 'volantis.dark.toggle()', group: 'darkMode'}

############################### Analytics ############################### > start
analytics: artalk
#  busuanzi: # https://cdn.dusays.com/bsz.js #volantis-static/libs/busuanzi/js/busuanzi.pure.mini.js #https://cdn.jsdelivr.net/gh/volantis-x/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js
#  leancloud: # 请使用自己的 id & key 以防止数据丢失
    # app_id: jzo6WNun9yu1j8JBPvqtrI07-MdYXbMMI # u9j57bwJod4EDmXWdxrwuqQT-MdYXbMMI
    # app_key: 2Pup6g4oWaBzosPxYVD0CFxV # jfHtEKVE24j0IVCGHbvuFClp
    # custom_api_server: https://lncld.nxingcloud.cf/ # 国际版一般不需要写，除非自定义了 API Server

custom_css:
  scrollbar: # 滚动条
    size: 4px
    border: 2px
  navbar:
    height: 60px
    width: auto # auto, max
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
  gap:
    h2: 40px # Spacing above H2 (only px unit)
    h3: 20px # Spacing above H3 (only px unit)
    h4: 13px # Spacing above H4 (only px unit)
    p: 1em # Paragraph spacing between paragraphs
    line_height: 1.6 # normal, 1.5, 1.75, 2 ...
  fontfamily:
    logofont:
      fontfamily: '"PingFang SC", "Varela Round", "Microsoft YaHei", Helvetica, Arial'
      #name: 'Varela Round'
      # url: volantis-static/media/fonts/VarelaRound/VarelaRound-Regular.ttf # https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts/VarelaRound/VarelaRound-Regular.ttf
    bodyfont:
      fontfamily: '"PingFang SC", "Varela Round", "Microsoft YaHei", Helvetica, Arial'
      #name: 'UbuntuMono'
      #url: volantis-static/media/fonts/UbuntuMono/UbuntuMono-Regular.ttf # https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts/UbuntuMono/UbuntuMono-Regular.ttf
    codefont:
      fontfamily: 'Monaco, UbuntuMono, Menlo'

open_graph:
  image: https://cdn.nxingcloud.co/images/logo/icon/logo_192x192-1bbba21164f88b5483eb56300e2b168d-9871be.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/android-chrome-192x192.png
  twitter_card: summary # summary_large_image , summary

# 结构化数据用于更改搜索结果的显示效果
structured_data:
  enable: true
  # 以下是覆盖配置, 默认配置见 scripts/helpers/structured-data/lib/config.js
  data:
    person:
      sns:
        - https://github.com/ZhangXQA
    logo:
      path: https://cdn.nxingcloud.co/images/logo/icon/logo_192x192-1bbba21164f88b5483eb56300e2b168d-9871be.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/android-chrome-192x192.png
      width: 192
      height: 192

