navbar:
  visiable: always # always, auto
  logo: # choose [img] or [icon + title]
    img: https://s1.ax1x.com/2022/05/13/OyMf1J.png # 导航栏首个图标
    icon:
    title:
  menu:
    - name: 首页
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 友链
      icon: fa-solid fa-link
      url: friends/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: about/
cover:
  height_scheme: full # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display: # 封面展示
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  title: 'NXing&南星'
  subtitle: '记录成长'
  search: The world is going to get better # search bar placeholder
  features:
    - name: 博客
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/
    - name: 云盘
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg # https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
      url: https://nxingcloud.co/zh-CN/
    - name: 源码
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f9ec.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://github.com/volantis-x/hexo-theme-volantis/
############################### Cover ############################### > end

pages:
  # 友链页面配置
  friends:
    layout_scheme: simple # simple: 简单布局, traditional: 传统布局

# 文章布局
article:
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, category, date, counter] #启用评论数量需在此添加
    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [updated, tags, walinecount, share]
    # 文章页脚组件
    footer_widget:
      # 版权声明组件 (for layout: post)
      copyright:
        enable: true

    meta_library:
      # 默认文章作者（可在 _data/author.yaml 中增加其他作者，并在 front-matter 中设置）
      # https://volantis.js.org/advanced-settings/#多人协同
      author:
        avatar: https://s1.ax1x.com/2022/05/13/OyS53F.jpg # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png
        name: NXing&南星
        url: /

comments:
  service: waline
  # 可选评论系统 #
  waline:
    placeholder: 快来发表自己的看法吧~ # 评论占位提示
    serverURL: https://waline.nxingcloud.co/ # Waline 的服务端地址（必填） 测试用地址: https://waline.vercel.app
    pageview: false # 浏览量统计
    comment: true  # 评论数统计

sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, music, category, tagcloud, lastupdate]
  # layout: docs/post 这类文章页面
  for_post: [toc, music]
  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger: 
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://s1.ax1x.com/2022/05/13/OyS53F.jpg
      shape: rectangle # circle, rectangle
      url: /about/
      title: NXing&南星
      subtitle: 一个大三在读生
      social:
        - icon: fa-solid fa-rss
          url: /
        - icon: fa-solid fa-envelope
          url: mailto:z1304242002@163.com
        - icon: fab fa-github
          url: https://github.com/ZhangXQA
        - icon: fa-solid fa-headphones-alt
          url: /
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      list_number: true
    # ---------------------------------------
     # music
    music:
      class: music
      pjaxReload: false # 切换页面时音乐不切换，继续播放
    # ---------------------------------------
    # category widget
    category:
      class: category
      header:
        title: 文章分类
        url: /categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      header:
        title: 热门标签
        url: /tags/
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2022/05/12'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          service: leancloud # busuanzi, leancloud

############################### Site Footer ############################### > start
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [social, license, analytics, br, copyright]
  social:
    - icon: fas fa-rss
      url: /
    - icon: fas fa-envelope
      url: mailto:z1304242002@163.com
    - icon: fab fa-github
      url: https://github.com/ZhangXQA
  # site copyright
  copyright: '[Copyright © since 2022 NXing&南星](/)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '[欢迎大家一起学习交流](/)'

############################### Plugins ############################### > start
plugins:
  # npm i hexo-wordcount
  wordcount:
    enable: false
  # Button Ripple Effect
  nodewaves:
    enable: true
  # fontawesome animation for fontawesome V5
  fontawesome_animation:
    enable: true
  # Typing Effects
  comment_typing:
    enable: false
  # 视差滚动效果 Slide Background
  parallax:
    enable: true
  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: true
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 647135926    # song id / playlist id / album id / search keyword
    order: random       # player play order, values: 'list', 'random'
    autoHide: false    # hide automaticaly
  # 暗黑模式 darkmode
  # 开关按钮：在 navbar.menu 中添加：
  # - name: 暗黑模式 # 可自定义
  #   icon: fa-solid fa-moon # 可自定义
  #   toggle: darkmode
  darkmode:
    enable: true
  # BBtalk https://bb.js.org
  bbtalk:
    # Set `plugins: ["bbtalk"]` to enable in front-matter
    # 不支持 Pjax
    js: https://unpkg.com/bbtalk@0.1.5/dist/bbtalk.js # BBtalk.js
    appId: 54VfCnvQDlDg15kUhSA0Ayy4-MdYXbMMI # your appID
    appKey: 6MmfrV9IVCG4HDpyxXQyw0XK # your appKEY
    serverURLs: https://54vfcnvq.api.lncldglobal.com # Request Api 域名

# 消息提示 
  # izitoast@1.4.0
  message:
    copyright:                           # 是否在复制时弹出版权提示，影响范围：ctrl+c、代码块复制按钮、右键复制选项
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'far fa-copyright light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red

### 自定义右键 新
rightmenus:
  enable: true
  # 右键自定义菜单区域
  menus:
    link:
      - {id: 'contact_the_author', name: '联系作者', icon: 'fa-solid fa-envelope', link: '/about', group: 'link'}
    #  - {id: 'help', name: '常见问题', icon: 'fa-solid fa-question', link: 'https://volantis.js.org/faqs/', group: 'link'}
    #  - {id: 'examples', name: '示例博客', icon: 'fa-solid fa-rss', link: 'https://volantis.js.org/examples/', group: 'link'}
    #  - {id: 'contributors', name: '加入社区', icon: 'fa-solid fa-fan', link: 'https://volantis.js.org/contributors/', group: 'link'}
      - hr
    #  - {id: 'source_docs', name: '本站源码', icon: 'fa-solid fa-code-branch', link: 'https://github.com/volantis-x/volantis-docs/', group: 'link'}
    #  - {id: 'source_theme', name: '主题源码', icon: 'fa-solid fa-code-branch', link: 'https://github.com/volantis-x/hexo-theme-volantis/', group: 'link'}
    darkMode:
      - {id: 'darkMode', name: '暗黑模式', icon: 'fa-solid fa-moon', event: 'volantis.dark.toggle()', group: 'darkMode'}

############################### Analytics ############################### > start
analytics:
  busuanzi: #volantis-static/libs/busuanzi/js/busuanzi.pure.mini.js #https://cdn.jsdelivr.net/gh/volantis-x/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js
  leancloud: # 请使用自己的 id & key 以防止数据丢失
    app_id: jzo6WNun9yu1j8JBPvqtrI07-MdYXbMMI # u9j57bwJod4EDmXWdxrwuqQT-MdYXbMMI
    app_key: 2Pup6g4oWaBzosPxYVD0CFxV # jfHtEKVE24j0IVCGHbvuFClp
    custom_api_server: https://lncld.nxingcloud.co # 国际版一般不需要写，除非自定义了 API Server